name: Release
on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.BOBPLUGIN_TOKEN }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: "14"

            - name: Install Dependencies And Build
              run: |
                  yarn install
                  yarn build

            - name: Commit files
              run: |
                  git config --global user.name 'ayang'
                  git config --global user.email '473033518@qq.com'
                  git commit -am "chore: update version"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.BOBPLUGIN_TOKEN }}

            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "release/*.bobplugin"
                  token: ${{ secrets.BOBPLUGIN_TOKEN }}
